server:
  port : 8070

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mongodb
  mail:
    host: smtp.gmail.com
    port: 587
    username: levchugovfortests@gmail.com
    password: Testtest05
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true