spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviesa
    username: postgres
    password: Kruwovica05
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: movies
    password: 1
    virtual-host: movies


  cloud:
    stream:
      bindings:
        vote:
          group: movie
          destination: vote.in
          contentType: application/json

      rabbit:
        bindings:
          vote:
            producer:
              exchange-type: fanout
            consumer:
              autoBindDlq: true
              acknowledgeMode: AUTO

logging:
  level:
    org:
      hibernate:
        type: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"