server:
  port : 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: movies
    password: 1
    virtual-host: movies

  cloud:
    stream:
      bindings:
        user:
          group: movie
          destination: user.in
          contentType: application/json

      rabbit:
        bindings:
          user:
            consumer:
              autoBindDlq: true
              acknowledgeMode: AUTO
